- name: put values
  template: src=values.yml dest=/tmp/prometheus_operator-{{ prometheus_operator_helm_release }}.yml

- name: enable stable repo
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com

- name: upgrade {{ prometheus_operator_helm_release }} release using a Helm chart
  shell: helm upgrade {{ prometheus_operator_helm_release }} stable/prometheus-operator --install --namespace {{ k8s_namespace }} -f /tmp/prometheus_operator-{{ prometheus_operator_helm_release }}.yml
