apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    prometheus: {{ prometheus_operator_helm_release }}-prometheus
  name: prometheus-{{ prometheus_operator_helm_release }}-prometheus-db-prometheus-{{ prometheus_operator_helm_release }}-prometheus-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ prometheus_operator_storage_class_name }}
