prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: {{ prometheus_operator_storage_class_name }}
          resources:
            requests:
              storage: 1Gi
